import { useState } from 'react';
import { VIOLATION_TYPES, PLATFORM_DATA } from '../lib/data';
import './ComplaintPage.css';

export function ComplaintPage() {
  const [form, setForm] = useState({
    agency: 'FTC',
    platform: '',
    violationType: '',
    businessName: '',
    businessType: '',
    description: '',
    impact: '',
    relief: '',
  });
  const [generated, setGenerated] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const platforms = Object.keys(PLATFORM_DATA);

  function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    setGenerating(true);

    setTimeout(() => {
      const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      const agencyFull = form.agency === 'FTC' ? 'Federal Trade Commission' : 'Department of Justice, Antitrust Division';
      const agencyAddr = form.agency === 'FTC'
        ? 'Federal Trade Commission\n600 Pennsylvania Avenue, NW\nWashington, DC 20580'
        : 'U.S. Department of Justice\nAntitrust Division\n950 Pennsylvania Avenue, NW\nWashington, DC 20530';

      const letter = `FORMAL COMPLAINT

${today}

${agencyAddr}

RE: Anti-Competitive Practices by ${form.platform}
Violation Type: ${form.violationType}
Filed on behalf of: ${form.businessName} (${form.businessType})

Dear ${agencyFull}:

I. INTRODUCTION

This complaint is filed pursuant to Section 5 of the Federal Trade Commission Act (15 U.S.C. Section 45) regarding anti-competitive practices by ${form.platform} in the artificial intelligence market.

${form.businessName}, a ${form.businessType.toLowerCase()} business, has been directly harmed by ${form.platform}'s ${form.violationType.toLowerCase()} practices as described herein.

II. FACTUAL BACKGROUND

${form.description}

III. ANTI-COMPETITIVE IMPACT

The above-described conduct constitutes ${form.violationType.toLowerCase()} in violation of federal antitrust law. Specifically:

${form.impact}

This conduct has resulted in:
- Reduced competition in the AI services market
- Higher costs for small businesses seeking AI solutions
- Diminished innovation due to market concentration
- Consumer harm through reduced choice and quality

IV. RELIEF REQUESTED

${form.relief || `We respectfully request that the ${agencyFull} investigate ${form.platform}'s ${form.violationType.toLowerCase()} practices and take appropriate enforcement action, including but not limited to:

1. Cease and desist order requiring ${form.platform} to end the described anti-competitive practices
2. Structural remedies to restore competitive market conditions
3. Monetary penalties commensurate with the harm caused
4. Mandatory data portability and interoperability requirements`}

V. COALITION SUPPORT

This complaint is supported by the LevelField Coalition, representing over 1,200 small businesses affected by anti-competitive AI practices. [Number] additional businesses have reported similar experiences with ${form.platform}.

VI. CONCLUSION

The anti-competitive practices described herein are causing ongoing harm to small businesses and to competition in the AI market. We urge prompt investigation and enforcement action.

Respectfully submitted,

${form.businessName}
via LevelField Anti-Monopoly AI Toolkit
Contact: complaints@levelfield.org

---
Generated by LevelField | Case Reference: LF-${Date.now().toString(36).toUpperCase()}
This is a demo document. No real complaint has been filed.`;

      setGenerated(letter);
      setGenerating(false);
    }, 2000);
  }

  return (
    <div className="complaint-page">
      <div className="container">
        <div className="page-header">
          <h1>Complaint Generator</h1>
          <p>Auto-draft formatted FTC or DOJ complaints. Fill in the specifics and we generate a formal complaint letter ready for filing.</p>
        </div>

        <div className="complaint-layout">
          <form className="complaint-form" onSubmit={handleGenerate}>
            <div className="form-section">
              <h3>Filing Details</h3>
              <div className="form-grid">
                <div className="form-group">
                  <label>Filing Agency</label>
                  <select value={form.agency} onChange={e => setForm({ ...form, agency: e.target.value })}>
                    <option value="FTC">Federal Trade Commission (FTC)</option>
                    <option value="DOJ">Department of Justice (DOJ)</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Target Platform</label>
                  <select value={form.platform} onChange={e => setForm({ ...form, platform: e.target.value })} required>
                    <option value="">Select platform...</option>
                    {platforms.map(p => <option key={p} value={p}>{p}</option>)}
                  </select>
                </div>
                <div className="form-group">
                  <label>Violation Type</label>
                  <select value={form.violationType} onChange={e => setForm({ ...form, violationType: e.target.value })} required>
                    <option value="">Select violation...</option>
                    {VIOLATION_TYPES.map(v => <option key={v} value={v}>{v}</option>)}
                  </select>
                </div>
              </div>
            </div>

            <div className="form-section">
              <h3>Your Business</h3>
              <div className="form-grid">
                <div className="form-group">
                  <label>Business Name</label>
                  <input
                    type="text"
                    placeholder="Your company name"
                    value={form.businessName}
                    onChange={e => setForm({ ...form, businessName: e.target.value })}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Business Type</label>
                  <select value={form.businessType} onChange={e => setForm({ ...form, businessType: e.target.value })} required>
                    <option value="">Select type...</option>
                    <option value="SaaS">SaaS Company</option>
                    <option value="Agency">Agency / Consultancy</option>
                    <option value="E-Commerce">E-Commerce</option>
                    <option value="Developer Tools">Developer Tools</option>
                    <option value="AI/ML Startup">AI/ML Startup</option>
                    <option value="Healthcare Tech">Healthcare Tech</option>
                    <option value="Financial Services">Financial Services</option>
                    <option value="Other">Other</option>
                  </select>
                </div>
              </div>
            </div>

            <div className="form-section">
              <h3>Complaint Details</h3>
              <div className="form-group">
                <label>Description of Anti-Competitive Conduct</label>
                <textarea
                  rows={4}
                  placeholder="Describe the specific anti-competitive behavior you've experienced..."
                  value={form.description}
                  onChange={e => setForm({ ...form, description: e.target.value })}
                  required
                />
              </div>
              <div className="form-group" style={{ marginTop: 'var(--space-4)' }}>
                <label>Business Impact</label>
                <textarea
                  rows={3}
                  placeholder="How has this behavior affected your business? Include revenue impact, lost customers, etc."
                  value={form.impact}
                  onChange={e => setForm({ ...form, impact: e.target.value })}
                  required
                />
              </div>
              <div className="form-group" style={{ marginTop: 'var(--space-4)' }}>
                <label>Relief Requested (optional)</label>
                <textarea
                  rows={3}
                  placeholder="What specific remedies are you seeking? Leave blank for standard relief language."
                  value={form.relief}
                  onChange={e => setForm({ ...form, relief: e.target.value })}
                />
              </div>
            </div>

            <button type="submit" className="btn btn-primary btn-lg" disabled={generating} style={{ width: '100%' }}>
              {generating ? (
                <>
                  <span className="spinner" />
                  Generating Complaint...
                </>
              ) : (
                'Generate Complaint Letter'
              )}
            </button>
          </form>

          {generated && (
            <div className="complaint-output">
              <div className="complaint-output-header">
                <h3>Generated Complaint</h3>
                <button
                  className="btn btn-sm btn-outline"
                  onClick={() => navigator.clipboard.writeText(generated)}
                >
                  Copy to Clipboard
                </button>
              </div>
              <pre className="complaint-letter">{generated}</pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
